name: HostingerDeploy

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 147.93.17.126
          username: u938941419
          port: 65002
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory
            cd domains/techminimaa.com
            
            # Install Composer 2 locally in the project directory
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php composer-setup.php --filename=composer.phar
            php -r "unlink('composer-setup.php');"
            
            # Initialize git repository
            if [ ! -d .git ]; then
              git init
              git remote add origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            else
              git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            fi
            
            # Fetch and reset to match remote
            git fetch origin main
            git checkout -f main || git checkout -b main
            git reset --hard origin/main
            
            # Create .env if it doesn't exist
            if [ ! -f .env ]; then
              cp .env.example .env
              sed -i 's/APP_ENV=local/APP_ENV=production/' .env
              sed -i 's/APP_DEBUG=true/APP_DEBUG=false/' .env
            fi
            
            # Create directory structure
            mkdir -p storage/framework/{sessions,views,cache}
            mkdir -p storage/logs
            mkdir -p bootstrap/cache
            
            # Set permissions
            chmod -R 755 .
            chmod -R 775 storage bootstrap/cache
            
            # Install dependencies using local composer
            php composer.phar install --no-dev --optimize-autoloader
            
            # Laravel commands
            php artisan key:generate --force
            php artisan storage:link --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force
            
            # Clear any previous caches
            php artisan cache:clear
            php artisan config:clear
            php composer.phar dump-autoload -o
            
      - name: Copy Build Files
        uses: appleboy/scp-action@master
        with:
          host: 147.93.17.126
          username: u938941419
          port: 65002
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "public/build/"
          target: "domains/techminimaa.com/"
          strip_components: 1