name: HostingerDeploy

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 147.93.17.126
          username: u938941419
          port: 65002
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory
            cd domains/techminimaa.com
            
            # Backup existing .env file if it exists
            if [ -f .env ]; then
              cp .env .env.backup
            fi
            
            # Pull latest changes
            git fetch origin main
            git checkout -f main
            git reset --hard origin/main
            
            # Restore .env file if backup exists
            if [ -f .env.backup ]; then
              cp .env.backup .env
            else
              cp .env.example .env
              # Set production environment variables
              sed -i 's/APP_ENV=local/APP_ENV=production/' .env
              sed -i 's/APP_DEBUG=true/APP_DEBUG=false/' .env
            fi
            
            # Install dependencies
            php composer.phar install --no-dev --optimize-autoloader
            
            # Set up storage directory
            mkdir -p storage/framework/{sessions,views,cache}
            mkdir -p storage/logs
            mkdir -p bootstrap/cache
            
            # Set proper permissions
            chmod -R 755 .
            chmod -R 775 storage bootstrap/cache
            
            # Setup public_html directory
            rm -rf public_html/*
            cp -r public/* public_html/
            
            # Create symbolic link for storage
            cd public_html
            ln -sf ../storage/app/public storage
            
            # Back to project root
            cd ..
            
            # Run Laravel commands
            php artisan key:generate --force
            php artisan storage:link --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force
            
            # Update index.php in public_html to point to correct paths
            sed -i 's|/../vendor/autoload.php|/../../vendor/autoload.php|' public_html/index.php
            sed -i 's|/../bootstrap/app.php|/../../bootstrap/app.php|' public_html/index.php
            
            # Clear caches
            php artisan cache:clear
            php artisan config:clear
            php composer.phar dump-autoload -o