name: Deploy Laravel Project to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Hostinger
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Composer Dependencies
      - name: Install Composer Dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-dev --prefer-dist --optimize-autoloader

      # Step 3: Configure SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 147.93.17.126 >> ~/.ssh/known_hosts

      # Step 4: Upload files to Hostinger
      - name: Push to Hostinger
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 147.93.17.126
          username: u938941419
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './'
          target: /home/u938941419/domains/techminimaa.com/public_html


      # Step 5: SSH into Hostinger to run migrations and clear cache
      - name: Run Post-Deployment Commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 147.93.17.126
          username: u938941419
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/u938941419/domains/techminimaa.com/public_html
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache