name: HostingerDeploy

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 147.93.17.126
          username: u938941419
          port: 65002
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory
            cd domains/techminimaa.com
            
            # Clone the repository
            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/TechMinimaaSolutions/techminimaa.git
            fi
            
            # Fetch and reset to latest changes
            git fetch origin main
            git checkout -f main || git checkout -b main
            git reset --hard origin/main
            
            # Create .env file
            cat > .env << 'EOL'
            APP_NAME=TechMinimaa
            APP_ENV=production
            APP_DEBUG=false
            APP_URL=https://techminimaa.com
            APP_KEY=base64:$(php -r "echo base64_encode(random_bytes(32));")

            LOG_CHANNEL=stack
            LOG_DEPRECATIONS_CHANNEL=null
            LOG_LEVEL=error

            DB_CONNECTION=mysql
            DB_HOST=193.203.184.211
            DB_PORT=3306
            DB_DATABASE=u938941419_techminimaa
            DB_USERNAME=u938941419_techminimaa
            DB_PASSWORD=Ashwanirai@1

            BROADCAST_DRIVER=log
            CACHE_DRIVER=file
            FILESYSTEM_DISK=local
            QUEUE_CONNECTION=sync
            SESSION_DRIVER=file
            SESSION_LIFETIME=120
            EOL
            
            # Install Composer dependencies
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php composer-setup.php --filename=composer.phar --2
            php -r "unlink('composer-setup.php');"
            php composer.phar install --no-dev --optimize-autoloader
            
            # Create necessary directories
            mkdir -p storage/framework/{sessions,views,cache}
            mkdir -p storage/logs
            mkdir -p bootstrap/cache
            mkdir -p storage/app/public
            mkdir -p public_html
            
            # Set directory permissions
            chmod -R 755 .
            chmod -R 775 storage bootstrap/cache
            chown -R u938941419:u938941419 .
            
            # Copy public files to public_html
            rm -rf public_html/*
            cp -r public/* public_html/
            
            # Create storage link manually
            mkdir -p public_html/storage
            cp -r storage/app/public/* public_html/storage/ 2>/dev/null || true
            
            # Update index.php paths
            sed -i 's|/../vendor/autoload.php|/../../vendor/autoload.php|' public_html/index.php
            sed -i 's|/../bootstrap/app.php|/../../bootstrap/app.php|' public_html/index.php
            
            # Clear all caches
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            
            # Generate new application key
            php artisan key:generate --force
            
            # Cache configurations
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            # Create MySQL user with correct host if it doesn't exist
            mysql -u u938941419_techminimaa -p"Ashwanirai@1" -e "
            CREATE USER IF NOT EXISTS 'u938941419_techminimaa'@'localhost' IDENTIFIED BY 'Ashwanirai@1';
            GRANT ALL PRIVILEGES ON u938941419_techminimaa.* TO 'u938941419_techminimaa'@'localhost';
            FLUSH PRIVILEGES;
            "
            
            # Run migrations
            php artisan migrate --force