name: HostingerDeploy

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 147.93.17.126
          username: u938941419
          port: 65002
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory
            cd domains/techminimaa.com
            
            # Backup existing .env file if it exists
            if [ -f .env ]; then
              cp .env .env.backup
            fi
            
            # Update Composer to version 2
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php composer-setup.php --filename=composer.phar --2
            php -r "unlink('composer-setup.php');"
            
            # Create or update .env file with correct database credentials
            cat > .env << 'EOL'
            APP_NAME=TechMinimaa
            APP_ENV=production
            APP_DEBUG=false
            APP_URL=https://techminimaa.com
            
            LOG_CHANNEL=stack
            LOG_LEVEL=error
            
            DB_CONNECTION=mysql
            DB_HOST=techminimaa.com
            DB_PORT=3306
            DB_DATABASE=u938941419_techminimaa
            DB_USERNAME=u938941419_techminimaa
            DB_PASSWORD=Ashwanirai@1
            
            BROADCAST_DRIVER=log
            CACHE_DRIVER=file
            FILESYSTEM_DISK=local
            QUEUE_CONNECTION=sync
            SESSION_DRIVER=file
            SESSION_LIFETIME=120
            EOL
            
            # Install dependencies with Composer 2
            php composer.phar install --no-dev --optimize-autoloader
            
            # Set up storage directory
            mkdir -p storage/framework/{sessions,views,cache}
            mkdir -p storage/logs
            mkdir -p bootstrap/cache
            
            # Set proper permissions
            chmod -R 755 .
            chmod -R 775 storage bootstrap/cache
            
            # Setup public_html directory
            mkdir -p public_html
            cp -r public/* public_html/
            
            # Create storage symlink manually
            mkdir -p public_html/storage
            if [ -d "storage/app/public" ]; then
              cp -r storage/app/public/* public_html/storage/
            fi
            
            # Update index.php in public_html
            cp public/index.php public_html/
            sed -i 's|/../vendor/autoload.php|/../../vendor/autoload.php|' public_html/index.php
            sed -i 's|/../bootstrap/app.php|/../../bootstrap/app.php|' public_html/index.php
            
            # Generate key and cache config
            php artisan key:generate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            # php artisan migrate --force