name: HostingerDeploy

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - 'routes/**'
      - 'resources/**'
      - 'database/migrations/**'
      - 'database/seeders/**'
      - 'tests/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only allow specific users to trigger deployments
    if: github.actor == 'TechMinimaaSolutions'
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd domains/techminimaa.com/public_html
            
            # Backup .env
            cp .env .env.backup
            
            # Pull only allowed changes
            git fetch origin main
            git reset --hard origin/main
            
            # Restore .env
            mv .env.backup .env
            
            # Clear and rebuild cache
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            # Set permissions
            chmod -R 755 .
            chmod -R 775 storage bootstrap/cache