name: HostingerDeploy

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Code Changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Go to your project directory
            cd domains/techminimaa.com/public_html
            
            # Backup current .env
            # cp .env .env.backup
            
            # Get only the new changes
            git fetch origin main
            git reset --hard origin/main
            
            # Restore .env
            # mv .env.backup .env
            
            # Clear and update Laravel cache
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan config:cache
            php artisan route:cache
            # php artisan optimize:clear
            chmod 644 .env

            