name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Step 2: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 4: Install Composer dependencies
      # - name: Install Composer Dependencies
      #   run: composer install --no-dev --prefer-dist --optimize-autoloader


      # Step 5: Set up Laravel
      - name: Setup Laravel
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan key:generate

      # Step 7: Set up SSH
      # - name: Set up SSH
      #   run: |
      #     set -e
      #     if [ -z ${{ secrets.SSH_PRIVATE_KEY }} ]; then
      #       echo "Error: SSH_PRIVATE_KEY is not set."
      #       exit 1
      #     fi
      #     mkdir -p ~/.ssh
      #     echo ${{ secrets.SSH_PRIVATE_KEY }} | tr -d '\r' > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan -H 147.93.17.126 >> ~/.ssh/known_hosts
      # Step 8: Deploy to Server
      - name: Deploy to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 147.93.17.126
          username: u938941419
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 65002
          script: |
            cd /home/u938941419/domains/techminimaa.com/public_html
            git pull origin main
            composer install --no-dev --prefer-dist --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache