name: HostingerDeploy

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Code Changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd domains/techminimaa.com/public_html
            
            # Get the list of changed files
            CHANGED_FILES=$(git diff --name-only HEAD HEAD~1)
            
            # Fetch latest changes without resetting everything
            git fetch origin main
            
            # Apply only the changes
            git checkout origin/main -- ${CHANGED_FILES}
            
            # Only clear specific caches based on what changed
            if [[ $CHANGED_FILES == *"routes"* ]]; then
              php artisan route:clear
              php artisan route:cache
            fi
            
            if [[ $CHANGED_FILES == *"views"* || $CHANGED_FILES == *"resources"* ]]; then
              php artisan view:clear
              php artisan view:cache
            fi
            
            if [[ $CHANGED_FILES == *"config"* ]]; then
              php artisan config:clear
              php artisan config:cache
            fi
            
            # Set permissions only for changed files
            for file in ${CHANGED_FILES}; do
              chmod 755 "$file" 2>/dev/null || true
            done
            
            echo "Updated files: ${CHANGED_FILES}"